export default {
	APP_PORT: process.env.APP_PORT || 8085,
	CREDENTIAL_REGISTRY: process.env.CREDENTIAL_REGISTRY || "0x744A02bE4ed550f20b245EB76f44a92A96bbCC8e",
	DIPLOMA_CLAIMS_VERIFIER: process.env.DIPLOMA_CLAIMS_VERIFIER || "0x53ed2822bBDD63013fDA74C4A988Ab3B18e39259",
	ELASTIC_NODE_URL: process.env.ELASTIC_NODE_URL || "",
	ELASTIC_APP_KEY: process.env.ELASTIC_APP_KEY || "",
	ELASTIC_APP_INDEX: process.env.ELASTIC_APP_INDEX || "logs-tokenized-api",
	ELASTIC_LOGGER_LEVEL: process.env.ELASTIC_LOGGER_LEVEL || "none",
	CONSOLE_LOGGER_LEVEL: process.env.CONSOLE_LOGGER_LEVEL || "debug"
}